models/EstadoPasajero.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Url;

/**
 * This is the model class for table "estado_pasajero".
 *
 * @property int $id_estado_pasajero
 * @property float $temperatura
 * @property string $sintomas_asociados
 * @property int $familiares_contagiados
 * @property int $id_pasajero
 * @property int $id_ruta
 *
 * @property Pasajero $pasajero
 * @property Ruta $ruta
 */
class EstadoPasajero extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'estado_pasajero';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['temperatura', 'sintomas_asociados', 'familiares_contagiados', 'id_pasajero', 'id_ruta'], 'required'],
            [['temperatura'], 'number'],
            [['familiares_contagiados', 'id_pasajero', 'id_ruta'], 'integer'],
            [['sintomas_asociados'], 'string', 'max' => 100],
            [['id_pasajero'], 'exist', 'skipOnError' => true, 'targetClass' => Pasajero::className(), 'targetAttribute' => ['id_pasajero' => 'id_pasajero']],
            [['id_ruta'], 'exist', 'skipOnError' => true, 'targetClass' => Ruta::className(), 'targetAttribute' => ['id_ruta' => 'id_ruta']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_estado_pasajero' => 'Codigo Estado Pasajero',
            'temperatura' => 'Temperatura',
            'sintomas_asociados' => 'Sintomas Asociados',
            'familiares_contagiados' => 'Familiares Contagiados',
            'id_pasajero' => 'Pasajero',
            'id_ruta' => 'Ruta',
        ];
    }

    /**
     * Gets query for [[Pasajero]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPasajero()
    {
        return $this->hasOne(Pasajero::className(), ['id_pasajero' => 'id_pasajero']);
    }

    /**
     * Gets query for [[Ruta]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRuta()
    {
        return $this->hasOne(Ruta::className(), ['id_ruta' => 'id_ruta']);
    }
}

controllers/EstadopasajeroController.php
<?php

namespace app\controllers;

use Yii;
use app\models\EstadoPasajero;
use app\models\EstadoPasajeroSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EstadopasajeroController implements the CRUD actions for EstadoPasajero model.
 */
class EstadopasajeroController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all EstadoPasajero models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EstadoPasajeroSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all EstadoPasajero models.
     * @return mixed
     */
    public function actionIndex_pasajero()
    {
        $searchModel = new EstadoPasajeroSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index_pasajero', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single EstadoPasajero model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new EstadoPasajero model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new EstadoPasajero();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_estado_pasajero]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing EstadoPasajero model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_estado_pasajero]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing EstadoPasajero model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the EstadoPasajero model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return EstadoPasajero the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = EstadoPasajero::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PasajeroController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Pasajero;
use app\models\PasajeroSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PasajeroController implements the CRUD actions for Pasajero model.
 */
class PasajeroController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pasajero models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PasajeroSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pasajero model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pasajero model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pasajero();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/estadopasajero/create', 'id' => $model->id_pasajero]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pasajero model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_pasajero]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pasajero model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pasajero model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pasajero the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pasajero::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/RutaController.php
<?php

namespace app\controllers;

use app\models\EstadoPasajero;
use app\models\EstadoPasajeroSearch;
use Yii;
use app\models\Ruta;
use app\models\RutaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RutaController implements the CRUD actions for Ruta model.
 */
class RutaController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Ruta models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RutaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Ruta model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {

        $estado_pasajero = EstadoPasajero::find()->where(['id_ruta' => $id])->all();
        return $this->render('view', [
            'model' => $this->findModel($id),
            'estado_pasajeros' => $estado_pasajero
        ]);
    }

    /**
     * Creates a new Ruta model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Ruta();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_ruta]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Ruta model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_ruta]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Ruta model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Ruta model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Ruta the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Ruta::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/estadopasajero/_form.php
<?php

use app\models\Ruta;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EstadoPasajero */
/* @var $form yii\widgets\ActiveForm */

$request = Yii::$app->request;
$id = $request->get('id');
?>

<div class="estado-pasajero-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'temperatura')->textInput() ?>

    <?= $form->field($model, 'sintomas_asociados')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'familiares_contagiados')->textInput() ?>

    <?= $form->field($model, 'id_pasajero')->hiddenInput(['value' => $id])->label(false) ?>

    <?= $form->field($model, 'id_ruta')->dropDownList(
        ArrayHelper::map(
            \app\models\Ruta::find()->asArray()->orderBy([
                'id_ruta' => SORT_DESC,
            ])->all(),
            'id_ruta',
            function ($model) {
                return $model['id_ruta'] . ' - ' . $model['lugar_salida'] . ' - ' . $model['lugar_llegada'];
            }
        )
    ) ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/estadopasajero/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EstadoPasajeroSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="estado-pasajero-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_estado_pasajero') ?>

    <?= $form->field($model, 'temperatura') ?>

    <?= $form->field($model, 'sintomas_asociados') ?>

    <?= $form->field($model, 'familiares_contagiados') ?>

    <?= $form->field($model, 'id_pasajero') ?>

    <?php // echo $form->field($model, 'id_ruta') ?>

    <div class="form-group">
        <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Limpiar', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/estadopasajero/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\EstadoPasajero */

$this->title = 'Crear Estado Pasajero';
$this->params['breadcrumbs'][] = ['label' => 'Estado Pasajeros', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="estado-pasajero-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/estadopasajero/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EstadoPasajeroSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Estado Pasajeros';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="estado-pasajero-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Crear Estado Pasajero', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id_estado_pasajero',
            'temperatura',
            'sintomas_asociados',
            'familiares_contagiados',
            'id_pasajero',
            //'id_ruta',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/estadopasajero/index_pasajero.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EstadoPasajeroSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Estado Pasajeros';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="estado-pasajero-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php // echo $this->render('_search', ['model' => $searchModel]); 
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            //'id_estado_pasajero',

            [
                'attribute' => 'id_ruta',
                'label' => 'Ruta',
                'format' => 'raw',
                'value' => function ($data) {
                    return Html::a($data->id_ruta, ['ruta/view', 'id' => $data->id_ruta]);
                },
            ],

            // [
            //     'attribute' => 'nombre_pasajero',
            //     'label' => 'Nombre',
            //     'format' => 'raw',
            //     'value' => function ($data) {
            //         return Html::a($data->nombre_pasajero, ['pasajero/view', 'id' => $data->nombre_pasajero]);
            //     },
            // ],

            // 'nombre',
            'temperatura',
            'sintomas_asociados',
            'familiares_contagiados',
            //'id_pasajero',
            //'id_ruta',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/estadopasajero/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\EstadoPasajero */

$this->title = 'Actualizar Estado Pasajero: ' . $model->id_estado_pasajero;
$this->params['breadcrumbs'][] = ['label' => 'Estado Pasajeros', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_estado_pasajero, 'url' => ['view', 'id' => $model->id_estado_pasajero]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="estado-pasajero-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/estadopasajero/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\EstadoPasajero */

$this->title = $model->id_estado_pasajero;
$this->params['breadcrumbs'][] = ['label' => 'Estado Pasajeros', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="estado-pasajero-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'id' => $model->id_estado_pasajero], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id_estado_pasajero], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Esta seguro que desea eliminar este item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_estado_pasajero',
            'temperatura',
            'sintomas_asociados',
            'familiares_contagiados',
            'id_pasajero',
            'id_ruta',
        ],
    ]) ?>

</div>